use std::path::PathBuf;

use crate::agent::{AgentConfig, AgentDef, RestartPolicy};
use crate::codegen::generate_process_compose;

fn make_agent(name: &str, restart: RestartPolicy) -> AgentDef {
    let config = Some(AgentConfig {
        restart,
        max_restarts: 5,
        backoff_seconds: 10,
        start_prompt: Some("Go".to_owned()),
        model: None,
        sandbox: None,
    });
    AgentDef {
        name: name.to_owned(),
        path: PathBuf::from(format!("/home/user/.rightclaw/agents/{name}")),
        identity_path: PathBuf::from(format!(
            "/home/user/.rightclaw/agents/{name}/IDENTITY.md"
        )),

        config,
        mcp_config_path: None,
        soul_path: None,
        user_path: None,
        memory_path: None,
        agents_path: None,
        tools_path: None,
        bootstrap_path: None,
        heartbeat_path: None,
    }
}

fn make_agent_no_config(name: &str) -> AgentDef {
    AgentDef {
        name: name.to_owned(),
        path: PathBuf::from(format!("/home/user/.rightclaw/agents/{name}")),
        identity_path: PathBuf::from(format!(
            "/home/user/.rightclaw/agents/{name}/IDENTITY.md"
        )),

        config: None,
        mcp_config_path: None,
        soul_path: None,
        user_path: None,
        memory_path: None,
        agents_path: None,
        tools_path: None,
        bootstrap_path: None,
        heartbeat_path: None,
    }
}

#[test]
fn single_agent_contains_name_and_paths() {
    let agents = vec![make_agent("watchdog", RestartPolicy::OnFailure)];
    let run_dir = PathBuf::from("/home/user/.rightclaw/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.contains("watchdog:"),
        "expected agent name as process key in:\n{output}"
    );
    assert!(
        output.contains("/home/user/.rightclaw/run/watchdog.sh"),
        "expected wrapper path in:\n{output}"
    );
    assert!(
        output.contains("/home/user/.rightclaw/agents/watchdog"),
        "expected working dir in:\n{output}"
    );
}

#[test]
fn multiple_agents_all_present() {
    let agents = vec![
        make_agent("alpha", RestartPolicy::Always),
        make_agent("beta", RestartPolicy::Never),
    ];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(output.contains("alpha:"), "expected alpha in:\n{output}");
    assert!(output.contains("beta:"), "expected beta in:\n{output}");
}

#[test]
fn restart_policy_on_failure_maps_correctly() {
    let agents = vec![make_agent("bot", RestartPolicy::OnFailure)];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.contains("restart: \"on_failure\""),
        "expected on_failure policy in:\n{output}"
    );
}

#[test]
fn restart_policy_always_maps_correctly() {
    let agents = vec![make_agent("bot", RestartPolicy::Always)];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.contains("restart: \"always\""),
        "expected always policy in:\n{output}"
    );
}

#[test]
fn restart_policy_never_maps_to_no() {
    let agents = vec![make_agent("bot", RestartPolicy::Never)];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.contains("restart: \"no\""),
        "expected 'no' for Never policy in:\n{output}"
    );
}

#[test]
fn defaults_when_no_config() {
    let agents = vec![make_agent_no_config("plain")];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.contains("restart: \"on_failure\""),
        "expected default on_failure in:\n{output}"
    );
    assert!(
        output.contains("backoff_seconds: 5"),
        "expected default backoff 5 in:\n{output}"
    );
    assert!(
        output.contains("max_restarts: 3"),
        "expected default max_restarts 3 in:\n{output}"
    );
}

#[test]
fn output_starts_with_generated_comment() {
    let agents = vec![make_agent("bot", RestartPolicy::OnFailure)];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.starts_with("# Generated by rightclaw"),
        "expected generated comment at start of:\n{output}"
    );
}

#[test]
fn output_contains_version_and_strict() {
    let agents = vec![make_agent("bot", RestartPolicy::OnFailure)];
    let run_dir = PathBuf::from("/tmp/run");
    let output = generate_process_compose(&agents, &run_dir).unwrap();

    assert!(
        output.contains("version:"),
        "expected version in:\n{output}"
    );
    assert!(
        output.contains("is_strict: true"),
        "expected is_strict in:\n{output}"
    );
}
