use crate::agent::types::SandboxMode;

/// Generate TOOLS.md content for an agent.
///
/// Contains environment-specific information: sandbox mode, file paths, MCP servers.
/// Fully generated by codegen — overwritten on every `rightclaw up`/`reload`.
pub fn generate_tools_md(agent_name: &str, sandbox_mode: &SandboxMode) -> String {
    let (sandbox_desc, inbox, outbox) = match sandbox_mode {
        SandboxMode::Openshell => (
            "OpenShell sandbox (k3s container with network and filesystem policies)",
            "/sandbox/inbox/",
            "/sandbox/outbox/",
        ),
        SandboxMode::None => (
            "no sandbox (direct host access)",
            "inbox/",
            "outbox/",
        ),
    };

    format!(
        "\
# Tool Notes

## Environment

- **Agent name:** {agent_name}
- **Sandbox:** {sandbox_desc}
- **Inbox:** `{inbox}` — inbound Telegram attachments are placed here
- **Outbox:** `{outbox}` — write files here to send via Telegram

## MCP Servers

The `right` MCP server is always available. Use it for memory, cron, and MCP management.
Additional servers can be added at runtime via `mcp_add`.
Run `mcp_list` to see all configured servers.
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tools_md_sandbox_openshell() {
        let result = generate_tools_md("test", &SandboxMode::Openshell);
        assert!(result.contains("## Environment"));
        assert!(result.contains("sandbox"));
        assert!(result.contains("/sandbox/inbox/"));
        assert!(result.contains("/sandbox/outbox/"));
    }

    #[test]
    fn tools_md_no_sandbox() {
        let result = generate_tools_md("test", &SandboxMode::None);
        assert!(result.contains("## Environment"));
        assert!(result.contains("no sandbox"));
        assert!(result.contains("inbox/"));
        assert!(result.contains("outbox/"));
    }
}
