[workspace]
changelog_config = "cliff.toml"
changelog_update = true
changelog_path = "CHANGELOG.md"
dependencies_update = false
git_release_enable = false
git_tag_enable = false
git_only = true
publish = false
semver_check = false

[[package]]
name = "rightclaw"
version_group = "workspace"

[[package]]
name = "rightclaw-bot"
version_group = "workspace"

[[package]]
name = "rightclaw-cli"
version_group = "workspace"
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_enable = true
git_tag_name = "v{{ version }}"
